// NOTE This file is auto-generated by Contentlayer

import { Activity, Job, Post, Recommendation, IceBaths, DocumentTypes, DataExports } from './types'
import { SourceProvideSchemaErrorJSON, SourceFetchDataErrorJSON } from 'contentlayer/core'

export * from './types'

export declare const allActivities: Activity[]
export declare const allJobs: Job[]
export declare const allPosts: Post[]
export declare const allRecommendations: Recommendation[]
export declare const iceBath: IceBaths

export declare const allDocuments: DocumentTypes[]


